### ISSUE TITLE
320*X display

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#3]
Главная
Список галерей
Фотогалерея
Страница с мероприятием будет исправлена в задаче https://github.com/ladyka/site-engine-of-some-nightclub/issues/76

**Comment by nikolaysalinder** [comment]
![Screenshot from 2019-07-09 17-01-15](https://user-images.githubusercontent.com/11499519/60894705-e6ddb280-a26b-11e9-8913-37e7efbb28b4.png)
![Screenshot from 2019-07-09 17-07-15](https://user-images.githubusercontent.com/11499519/60894829-20aeb900-a26c-11e9-9897-758fb4816a0b.png)

**Comment by nikolaysalinder** [comment]
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-17-07-52](https://user-images.githubusercontent.com/11499519/60895060-9a46a700-a26c-11e9-9d12-a4930ccf4dc6.png)
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-17-07-73](https://user-images.githubusercontent.com/11499519/60895137-c6fabe80-a26c-11e9-9c22-dbaf4f24e417.png)
