### ISSUE TITLE
Top banner.2

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#43]
1. Store settings in the database
2. Change settings admin
3. Settings : image, eventId, end date
4. Show only one banner.

**Comment by ladyka** [comment]
В настройках сайта должна быть возможность выбрать событие на которое будет ссылаться верхний баннер.

**Comment by ladyka** [comment]
https://github.com/ladyka/site-engine-of-some-nightclub/issues/98

**Comment by SashAlhina** [comment]
На данный момент при нажатии на баннер пользователь переадресовывается на подробную информацию о событии.
Данное ишью закрываю, т.к. остальные доп изменения будут в ишью #98
