### ISSUE TITLE
Space disk checker

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by serjeshs** [comment]
Сервис по крону (например раз в час) будет проверять соотношение доступного места к размеру диска, если соотношение меньше критического (например 0,3), то будет остылаться письмо на ящик админа.
