### ISSUE TITLE
Сохранение на диск внешних изображений.

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#46]
Создать сервис, в нем будет один метод без параметров.
В этом методе получить список всех событий (EventEntity).
для каждого события : 
Если обложка(coverUri) события находится вне сайта, ссылка начинается с http:// или https://.
Скачать это изображение. (используя CloseableHttpClient)
Сохранить используя StorageService. Там есть метод 
`public String store(MultipartFile multipartFile) throws IOException {`
который нужно разделить на 2, один будет вызывать второй.
второй метод будет вызыват это сервис, который и получит ссылку на картинку новую.
Эту ссылку сохранить в событии.

получится примерно так : 
Вместо https://pp.userapi.com/c841137/v841137810/7580a/l2RQOIh2G9E.jpg
будет
/files/2019/2/6666k.jpg

**Comment by serjeshs** [comment]
Про разделение метода store(MultipartFile multipartFile) не совсем понятно, какой функционал будут выполнять части. По тексту получается какая то зацикленность.. 
Возможно имеется в виду, что одна часть разделенного метода вызывает новый сервис а тот в свою очередь обратится ко второй части и она отработает - сохранит?

**Comment by ladyka** [comment]
примерно так 
```

   public String store(MultipartFile multipartFile) throws IOException {
        String originalFilename = multipartFile.getOriginalFilename();
        originalFilename = (originalFilename != null)? originalFilename : "null";
        InputStream inputStream = multipartFile.getInputStream();
        return store(originalFilename, inputStream);
    }

    public String store(String originalFilename, InputStream inputStream) throws IOException {
        LocalDateTime date = LocalDateTime.now();
        String directoryOut = date.getYear() + File.separator + date.getMonthValue();
        new File(customSettings.getFilesDirectory() + File.separator + directoryOut).mkdirs();
        String fileName = (int) (Math.random() * 10000) + originalFilename.substring(originalFilename.length() - 5);
        File outFile = new File(customSettings.getFilesDirectory() + File.separator + directoryOut + File.separator + fileName);
        OutputStream outStream = new FileOutputStream(outFile);
        IOUtils.copy(inputStream, outStream);
        outStream.close();
        FileEntity fileEntity = new FileEntity();
        fileEntity.setFilePath(directoryOut + File.separator + fileName);
        fileEntity = filesRepository.save(fileEntity);
        return fileEntity.getFilePath();
    }
```

**Comment by human453453467** [comment]
#47
