### ISSUE TITLE
Стоимость билетов.

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#49]
Пользователю-Администратору нужно выставлять цену,которая активна к определённый момент времени.
Цена должна содержать (создать новую сущность "event_ticket_price"):
стоимость.
количество (int)
тип (танцпол/столик)
событие,
время начала её активности, 
время окончания её активности,
кто установил.

их можно добавлять и редактировать, удалять нельзя, делать не видимыми,
Для события отображать самый дешевый вариант на данный момент времени.

При покупке билета ссылка на цену должна быть прикреплена к заказу.
Если кто-то купил билет по этой цене, то редактировать её уже нельзя.

**Comment by human453453467** [comment]
#57

**Comment by human453453467** [comment]
I've decided to do IT tests in another way for subsequent tasks. With [rider lib](https://github.com/database-rider/database-rider) help.
