### ISSUE TITLE
Соблюдение единого дизайна кнопок/границ разделов на Главной странице/ Афиша

### ISSUE THREAD

**Issue by SashAlhina** [ladyka/site-engine-of-some-nightclub#72]
- Обрезана кнопка [Купить билет (подробнее)] в события по месяцам в отличие от такой же кнопки в июньских мероприятиях:
![купить билет кнопка](https://user-images.githubusercontent.com/51112674/58908775-27e92100-871a-11e9-9436-64aedae2c4a8.png)
Кнопка не должна быть обрезана, желательно иметь единый вид

- Окно мероприятий узкое и длинное, что неудобно для пользователя , не везде единый дизайн:
![дизайн](https://user-images.githubusercontent.com/51112674/58908923-75fe2480-871a-11e9-8b2f-00d003725987.png)
Рекомендую саму страницу с афишей сделать шире

- Кнопка  [Купить билет (подробнее)] расположена не внизу поста,что выглядит неаккуратно:
![расположение кнопки](https://user-images.githubusercontent.com/51112674/58909101-eefd7c00-871a-11e9-9d7c-fc6c315598e7.png)
Рекомендую кнопку расположить в конце поста о мероприятии, справа

**Comment by nikolaysalinder** [comment]
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-20-07-62](https://user-images.githubusercontent.com/11499519/60908593-edc4ef00-a284-11e9-80c4-86eb6f4a98ab.png)
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-20-07-15](https://user-images.githubusercontent.com/11499519/60908596-eef61c00-a284-11e9-97d1-f33663b01ef0.png)
1.5

**Comment by SashAlhina** [comment]
Новый вид кнопок сделан отлично! Остаётся вопрос: будем ли мы что-то делать с границами страницы? или на это создать отдельный issue?

**Comment by nikolaysalinder** [comment]
Я немного расширил страницу, убрав ненужные внтурренние отступы. Возможно есть смысл вертикальньый ритм дорабоатть.

**Comment by SashAlhina** [comment]
@nikolaysalinder

**Comment by SashAlhina** [comment]
На данный момент дизайн страницы скорректирован, закрываю
