### ISSUE TITLE
Лишний символ (точка) в информации о событиях на завтра

### ISSUE THREAD

**Issue by SashAlhina** [ladyka/site-engine-of-some-nightclub#73]
Лишний символ (точка) в информации о событиях на завтра

**Шаги:**
1. Открыть https://www.republic-club.by
2. Просмотреть внешний вид мероприятия на завтра

**Ожидаемый результат:**
Нет лишних символов/знаков на странице

Скрин: 
![точка на завтрашнем мероприятии](https://user-images.githubusercontent.com/51112674/58909665-57009200-871c-11e9-9a7e-113e9c33bc81.png)

**Comment by nikolaysalinder** [comment]
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-17-07-54](https://user-images.githubusercontent.com/11499519/60898931-4ccd3880-a272-11e9-924b-02d007a6cbb4.png)

**Comment by SashAlhina** [comment]
на данный момент на http://qa.republic-club.by/ лишний символ отсутствует. Исправлено.
