### ISSUE TITLE
Вкладка "Бюро находок и информация" выделена  красным шрифтом в отличии от остальных вкладок

### ISSUE THREAD

**Issue by SashAlhina** [ladyka/site-engine-of-some-nightclub#74]
Вкладка "Бюро находок и информация" выделена  красным шрифтом в отличии от остальных вкладок
Данная вкладка не является основной на сайте, поэтому не вижу причин для ее выделения

Mobile+Dekstop

Шаги:
1. Открыть https://www.republic-club.by
2. Просмотреть стиль и вид основных вкладок сайта

Ожидаемый результат:
Вкладки выдержаны в одном стиле

Скрин:
![бюро](https://user-images.githubusercontent.com/51112674/58910062-4f8db880-871d-11e9-907f-9ad08d9807be.png)

**Comment by ladyka** [comment]
Это требование заказчика
