### ISSUE TITLE
Полный просмотр афиши.

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#76]
При нажатии на афишу на сайте она открывалась в размере, на весь экран.
Предложить варианты и заимплеменить понравившийся.
уменьшенная копия будет доступна по текущей ссылке,
По нажатию будет та же ссылка и поствикс original.

Дополнительно : 
адаптировать страницу к разрешениям в ширину от 320 пикселей.

**Comment by nikolaysalinder** [comment]
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-20-07-62](https://user-images.githubusercontent.com/11499519/60908502-b2c2bb80-a284-11e9-8c71-c11464a06285.png)
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-09-20-07-15](https://user-images.githubusercontent.com/11499519/60908533-c53cf500-a284-11e9-80a4-d7711fa3a145.png)
1, 5 часа.

**Comment by nikolaysalinder** [comment]
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-10-17-07-56](https://user-images.githubusercontent.com/11499519/60976764-f70e9400-a336-11e9-93d4-4e8c0d1a8ed1.png)
![AwesomeScreenshot-RE-PUBLIC-RE-PUBLIC-Club-Minsk-2019-07-10-17-07-08](https://user-images.githubusercontent.com/11499519/60976848-21605180-a337-11e9-9263-38c7f636ccf0.png)
3 часа.

**Comment by SashAlhina** [comment]
Не получается открыть Афишу в полном размере, как на скрине.
Тестила так:
1. Зашла на сайт http://qa.republic-club.by
2. Выбрала мероприятие, нажала на название мероприятия, которое работает как активная ссылка
3. После перехода на страницу описания мероприятия навела курсор на  саму афишу

Актуальный результат: курсор мыши превратился в указатель (как и должно быть), но при нажатии ничего не происходит, т.е. картинка не увеличилась и не открылась в увеличенном размере

Ожидаемый результат: Афиша откроется как на скрине, в увеличенном варианте

**Comment by SashAlhina** [comment]
протестировано:
При нажатии на картинку в разделе "Афиша" пользователь переадресовывается на описание мероприятия. При нажатии на картинку в описании мероприятия - картинка увеличивается, при этом не растягиваясь на всю страницу и не выходит за рамки страницы.
