### ISSUE TITLE
Съехали строки с описанием и ценой продукта в "Заказ столика и просмотр меню"

### ISSUE THREAD

**Issue by SashAlhina** [ladyka/site-engine-of-some-nightclub#80]
_Съехали строки в "Заказ столика и просмотр меню" из-за чего непонятно к какому из продуктов относятся описание,граммовка,цена,а так же из-за этого кнопка для выбора количества продукта расположена не напротив самого продукта._

**Протестировано на:**
Chrome for Dekstop v. 75.0.3770.100 
Chrome for mobile v. 75.0.3770.101

**Шаги:**
1. Зайти на сайт
2. Нажать на вкладку "Заказ столика и просмотр меню"
3. Проскролить всю страницу и проверить расположение описания продуктов, кнопок и т.п.

**Ожидаемый результат:** все поля,расстояния между полями и расположение кнопок выдержано в одном стиле

**Актуальный результат:** Между некоторыми продуктами есть лишние пробелы, что привело к некорректному разбиению информации

**Скрины:**

![гарниры соусы 2](https://user-images.githubusercontent.com/51112674/60920643-5de16e00-a2a1-11e9-84c4-eae6a8b8a03d.png)
![продукты](https://user-images.githubusercontent.com/51112674/60920672-6b96f380-a2a1-11e9-9650-beddaa15ced0.png)

**Comment by ladyka** [comment]
Если описания нет - новая строка не добавляется.

**Comment by SashAlhina** [comment]
исправлено
