### ISSUE TITLE
Опечатка в заголовке "Гарниры соусы" во вкладке "Заказ столика и просмотр меню"

### ISSUE THREAD

**Issue by SashAlhina** [ladyka/site-engine-of-some-nightclub#81]
_Опечатка в заголовке "Гарниры соусы" во вкладке "Заказ столика и просмотр меню"_

**Шаги:**
1. Открыть сайт
2. Открыть вкладку "Заказ столика и просмотр меню"
3. Проверить написание заголовка "Гарниры соусы" 

**Ожидаемый результат:** заголовок указан без опечаток

**Актуальный результат:** заголовок указан с опечаткой "Гариниры соусы"

**Предлагаю:**  Исправить на: ГАРНИРЫ и СОУСЫ (т.е. добавить ещё "и" чтобы заголовок смотрелся более приемлемо)

**Скрин:**
![гарниры описка](https://user-images.githubusercontent.com/51112674/60921147-7ef68e80-a2a2-11e9-839b-0ae23f790ef9.png)

**Comment by ladyka** [comment]
Это ишью должно быть пофикшено на проде.

**Comment by SashAlhina** [comment]
@ladyka 
На текущий момент на проде исправлено слово "Гарниры"
Предлагаю либо добавить запятую: Гарниры, соусы либо слэш: Гарниры/ Соусы либо так: Гарниры и Соусы , чтобы с точки зрения русского языка это выглядело гармоничнее

**Comment by ladyka** [comment]
@SashAlhina Исправил на "Гарниры и соусы"
