### ISSUE TITLE
Покупка билета и еды на событие

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#85]
Позволить пользователю купить билет.
Если в заказе есть столик, позволить заказать меню на него.
Скрыть пункт "Заказ столика и просмотр меню"

**Comment by SashAlhina** [comment]
При попытке покупки билета через сайт идет переадресация на сторонние ресурсы с данным мероприятием: http://wakeupagency.by , например, или vk и т.п. Т.е. на самом сайте репаблика покупка билета не осуществима (по крайней мере из тех мероприятий, которые есть сейчас).
Если пробовать оформить заказ столика + выбор меню("вкладка заказ столика и просмотр меню") - при заполнении  формы нужно выбрать мероприятие, а сам список мероприятий пуст и соответственно так проверить тоже нет возможности (см скрин ниже)

![заказ столика на мероприятие](https://user-images.githubusercontent.com/51112674/61649334-f3c1c380-acb9-11e9-8543-a0e39c787183.png)

**Comment by SashAlhina** [comment]
@ladyka 
Дизайн страницы "Покупка билета"

1.Выбираем событие и нажимаем [Купить билет]
2. Еще раз нажимаем [Купить билет]

Текущий результат:

Открывается окно "Покупка билета" для выбора количества билетов и дальнейшей покупки. 

Разный дизайн для билетов Танцпола и Столика, что путает пользователя.

На картинке изображен достаточно маленький танцпол, если пользователь никогда не был в клубе - это создает некорректное впечатление о размерах клуба.

Кнопка [Далее] едва заметна, не смотря на синюю подсветку

Ожидаемый/желаемый результат:


На самой картинке клуба танцпол изобразить чуть больше, ближе к реальному соотношению. 

Сделать единый дизайн, например:
На картинке на месте Танцпола добавить кнопку добавления количества билетов, таким образом пользователь нажав на танцпол выбирает количество билетов и нажав на столики выбирает места.

Добавить видимый контур кнопке "Далее",например такой же как при наведении на неё - тогда пользователь быстрее сориентируется, что ему делать дальше.

**Comment by SashAlhina** [comment]
На этапе "Общая информация о пользователе" юзер может пойти далее не поставив галочки в строках 
![Общая инфа](https://user-images.githubusercontent.com/51112674/62808922-311fb100-bb02-11e9-856c-f549ecbac1f3.png)

**Comment by SashAlhina** [comment]
Уже занятые столики и те , которые пользователь выбирает прямо сейчас - одного цвета и вида, что некорретно. Должно быть отличие по дизайну, иначе юзер запутается какие же места его

**Comment by SashAlhina** [comment]
При выборе еды на данный момент все те же ошибки указанные  в issue https://github.com/ladyka/site-engine-of-some-nightclub/issues/80
шаги:
1.Выбираем событие и нажимаем [Купить билет]
2. Еще раз нажимаем [Купить билет]
3. выбираем места за столиком
4. Нажимаем "далее" и еще раз "далее"

Актуальный результат: 
Между некоторыми продуктами есть лишние пробелы, что привело к некорректному разбиению информации
Описка в разделе "Гариниры"
При наведении на кнопку увеличения количества товара- значок мышки в виде стрелки не превращается в руку

Ожидаемый результат:
все поля,расстояния между полями и расположение кнопок выдержано в одном стиле
нет опечаток
Стрелка меняется на знак руки для выбора количества товара

Дублирую скрины сюда:
![гарниры описка](https://user-images.githubusercontent.com/51112674/62809491-c5d6de80-bb03-11e9-9dc2-5ed2c675ccdf.png)
![гарниры соусы 2](https://user-images.githubusercontent.com/51112674/62809492-c5d6de80-bb03-11e9-8b1c-872aa54e23c8.png)

**Comment by ladyka** [comment]
1. Принять правила клуба.

**Comment by ladyka** [comment]
2. Если поле пустое описания. - скрыть

**Comment by SashAlhina** [comment]
@ladyka 
Работает корректно:

- Позволить пользователю купить билет.

- Если в заказе есть столик, позволить заказать меню на него.

- Если пользователь не согласился с правилами клуба - появляется уведомление

Не исправлено:

- Скрыть пункт "Заказ столика и просмотр меню"

!! Рекомендации:

- Стрелка меняется на знак руки для выбора количества блюд при предзаказе
- После того, как пользователю появляется сообщение, что нужно принять правила клуба - рекомендую переадресовать его обратно на второй шаг, где эти самые правила и находятся. Потому как сразу непонятно куда нажимать, где и с чем соглашаться
- Сделать "Х" на окошке "Покупка билетов" справа в верхнем углу, чтобы было понятно как его закрыть при необходимости

**Comment by ladyka** [comment]
@SashAlhina Перенес рекомнедации в другую задачу.
#95
