### ISSUE TITLE
Продажа билетов.

### ISSUE THREAD

**Issue by ladyka** [ladyka/site-engine-of-some-nightclub#86]
Позволить продавать билеты только на танцпол или только на столик.

**Comment by SashAlhina** [comment]
@ladyka 
На данный момент если в событии присутствует и столик и танцпол, то пользователь может одновременно оформить билеты и на танцпол и на столик, только способы выбора количества билетов разные:

- При выборе количества билетов на танцпол юзеру необходимо кликать на кнопку справа

- При выборе количества билетов за столиком - кликать на схему клуба, на сами столики.

В целом, одновременная возможность купить билеты и туда и туда имеет право на существование. 

На картинке изображен достаточно маленький танцпол, если пользователь никогда не был в клубе - это создает некорректное впечатление о размерах клуба.

Предлагаю на рассмотрение создание единого дизайна для покупки билетов на Танцпол и за столики:
На картинке на месте Танцпола добавить кнопку добавления количества билетов, таким образом пользователь нажав на танцпол выбирает количество билетов и нажав на столики выбирает места.

![Покупка билетов 2](https://user-images.githubusercontent.com/51112674/62808573-1d277f80-bb01-11e9-8869-c7984f77939c.png)

**Comment by SashAlhina** [comment]
На данный момент такая возможность реализована через вкладку "Операции над событиями".
Администратор может создать событие и сделать доступной покупку билетов только на танцпол или только за столик.
